### ISSUE TITLE
[style only] replace fixed height

### ISSUE THREAD

**Issue by tieppt** [vanhtuan0409/redux-react-sample-coffee#1] opened 2017-12-07 07:39 UTC
https://github.com/vanhtuan0409/redux-react-sample-coffee/blob/f6d24702c33923e13468160dac94a62de36c25b1/src/containers/OrderForm/steps/StepLayout/style.styl#L37-L40

`min-height: 100%;`

Screenshot:

![vanhtuan0409 github io_hackathon-react-with-redux_ iphone 6](https://user-images.githubusercontent.com/7151365/33706567-1a015568-db67-11e7-855f-dd131ac2e197.png)

**Comment by vanhtuan0409** [comment] 2017-12-07 08:09
Can you explain more what side effect caused by having a fixed height?

**Comment by tieppt** [comment] 2017-12-07 08:57
please see the updated screenshot.

**Comment by vanhtuan0409** [comment] 2017-12-07 09:08
fixed in 3054c37c83309990d01f47869d4b8228443b4e58
I know this is a quick hack but don't want to spend time rewriting CSS

**Closed as completed by vanhtuan0409** 2017-12-07 09:08 UTC
